### ISSUE TITLE
[Eventropies] - Change naming scheme to match referenced paper

### ISSUE THREAD

**Issue by andreamalhera** [lmu-dbs/feeed#13]
https://github.com/lmu-dbs/feeed/blob/834e823d646210e0b761fdea25b12e3ddc0547b4/README.md?plain=1#L49

Paper: C. O. Back, S. Debois, and T. Slaats, “Entropy as a measure of log variability,” Journal on Data Semantics, vol. 8, no. 2, Jun 2019.

`entropies` --> `eventropies`
`entropy_trace` --> `eventropy_trace`
`entropy_prefix` --> `eventropy_prefix`
`entropy_prefix_flattened` --> `eventropy_prefix_flattened`
`entropy_global_block` --> `eventropy_global_block`
`entropy_global_block_flattened` --> `eventropy_global_block_flattened`
`entropy_lempel_ziv` --> `eventropy_lempel_ziv`
`entropy_lempel_ziv_flattened` --> `eventropy_lempel_ziv_flattened`
`entropy_k_block_diff_1` --> `eventropy_k_block_diff_1`
`entropy_k_block_diff_3` --> `eventropy_k_block_diff_3`
`entropy_k_block_diff_5` --> `eventropy_k_block_diff_5`
`entropy_k_block_ratio_1` --> `eventropy_k_block_ratio_1`
`entropy_k_block_ratio_3` --> `eventropy_k_block_ratio_3`
`entropy_k_block_ratio_5` --> `eventropy_k_block_ratio_5`
`entropy_knn_3` --> `eventropy_knn_3`
`entropy_knn_5` --> `eventropy_knn_5`
`entropy_knn_` --> `eventropy_knn_7`

**Comment by anirudh027** [comment]
Opened a PR to solve the naming convention

**Comment by anirudh027** [comment]
@andreamalhera we can close this issue right?

**Comment by andreamalhera** [comment]
> @andreamalhera we can close this issue right?

Not yet. We will close this issue when #17 is merged, which we will do when #14 is integrated into [#13 branch](https://github.com/lmu-dbs/feeed/tree/13-eventropies-change-naming-scheme-to-match-referenced-paper). In other words, we plan to close this and #14 together with the ultimate merge of #17.
